module(load="imudp")
module(load="imtcp")
module(load="imtls")

# UDP on port 514
input(type="imudp" port="514")

# TLS encrypted TCP on 6514
input(
  type="imtcp"
  port="6514"
  StreamDriver="gtls"
  StreamDriverMode="1"
  StreamDriverAuthMode="anon"
)

# TLS 
global(
  DefaultNetStreamDriverCAFile="/etc/rsyslog-tls/server.crt"
  DefaultNetStreamDriverCertFile="/etc/rsyslog-tls/server.crt"
  DefaultNetStreamDriverKeyFile="/etc/rsyslog-tls/server.key"
)

#Timestamps and source
$template AegisLog,"%timegenerated% %HOSTNAME% %syslogtag%%msg%\n"
*.* /var/log/aegisfa/syslog.log;AegisLog